/*
 * This file is generated by jOOQ.
 */
package com.billa.jooq.tables.daos;


import com.billa.jooq.tables.Employee;
import com.billa.jooq.tables.records.EmployeeRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeDao extends DAOImpl<EmployeeRecord, com.billa.jooq.tables.pojos.Employee, Long> {

    /**
     * Create a new EmployeeDao without any configuration
     */
    public EmployeeDao() {
        super(Employee.EMPLOYEE, com.billa.jooq.tables.pojos.Employee.class);
    }

    /**
     * Create a new EmployeeDao with an attached configuration
     */
    public EmployeeDao(Configuration configuration) {
        super(Employee.EMPLOYEE, com.billa.jooq.tables.pojos.Employee.class, configuration);
    }

    @Override
    public Long getId(com.billa.jooq.tables.pojos.Employee object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.billa.jooq.tables.pojos.Employee> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Employee.EMPLOYEE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.billa.jooq.tables.pojos.Employee> fetchById(Long... values) {
        return fetch(Employee.EMPLOYEE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.billa.jooq.tables.pojos.Employee fetchOneById(Long value) {
        return fetchOne(Employee.EMPLOYEE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.billa.jooq.tables.pojos.Employee> fetchOptionalById(Long value) {
        return fetchOptional(Employee.EMPLOYEE.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.billa.jooq.tables.pojos.Employee> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employee.EMPLOYEE.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.billa.jooq.tables.pojos.Employee> fetchByName(String... values) {
        return fetch(Employee.EMPLOYEE.NAME, values);
    }

    /**
     * Fetch records that have <code>marks BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.billa.jooq.tables.pojos.Employee> fetchRangeOfMarks(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Employee.EMPLOYEE.MARKS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>marks IN (values)</code>
     */
    public List<com.billa.jooq.tables.pojos.Employee> fetchByMarks(Integer... values) {
        return fetch(Employee.EMPLOYEE.MARKS, values);
    }
}
