/*
 * This file is generated by jOOQ.
 */
package com.billa.jooq.tables.daos;


import com.billa.jooq.tables.Orders;
import com.billa.jooq.tables.records.OrdersRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersDao extends DAOImpl<OrdersRecord, com.billa.jooq.tables.pojos.Orders, Long> {

    /**
     * Create a new OrdersDao without any configuration
     */
    public OrdersDao() {
        super(Orders.ORDERS, com.billa.jooq.tables.pojos.Orders.class);
    }

    /**
     * Create a new OrdersDao with an attached configuration
     */
    public OrdersDao(Configuration configuration) {
        super(Orders.ORDERS, com.billa.jooq.tables.pojos.Orders.class, configuration);
    }

    @Override
    public Long getId(com.billa.jooq.tables.pojos.Orders object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.billa.jooq.tables.pojos.Orders> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Orders.ORDERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.billa.jooq.tables.pojos.Orders> fetchById(Long... values) {
        return fetch(Orders.ORDERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.billa.jooq.tables.pojos.Orders fetchOneById(Long value) {
        return fetchOne(Orders.ORDERS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.billa.jooq.tables.pojos.Orders> fetchOptionalById(Long value) {
        return fetchOptional(Orders.ORDERS.ID, value);
    }

    /**
     * Fetch records that have <code>person_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.billa.jooq.tables.pojos.Orders> fetchRangeOfPersonId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Orders.ORDERS.PERSON_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>person_id IN (values)</code>
     */
    public List<com.billa.jooq.tables.pojos.Orders> fetchByPersonId(Long... values) {
        return fetch(Orders.ORDERS.PERSON_ID, values);
    }

    /**
     * Fetch records that have <code>amount BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.billa.jooq.tables.pojos.Orders> fetchRangeOfAmount(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Orders.ORDERS.AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<com.billa.jooq.tables.pojos.Orders> fetchByAmount(Integer... values) {
        return fetch(Orders.ORDERS.AMOUNT, values);
    }
}
