/*
 * This file is generated by jOOQ.
 */
package com.billa.jooq.tables.daos;


import com.billa.jooq.tables.Person;
import com.billa.jooq.tables.records.PersonRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonDao extends DAOImpl<PersonRecord, com.billa.jooq.tables.pojos.Person, Long> {

    /**
     * Create a new PersonDao without any configuration
     */
    public PersonDao() {
        super(Person.PERSON, com.billa.jooq.tables.pojos.Person.class);
    }

    /**
     * Create a new PersonDao with an attached configuration
     */
    public PersonDao(Configuration configuration) {
        super(Person.PERSON, com.billa.jooq.tables.pojos.Person.class, configuration);
    }

    @Override
    public Long getId(com.billa.jooq.tables.pojos.Person object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.billa.jooq.tables.pojos.Person> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Person.PERSON.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.billa.jooq.tables.pojos.Person> fetchById(Long... values) {
        return fetch(Person.PERSON.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.billa.jooq.tables.pojos.Person fetchOneById(Long value) {
        return fetchOne(Person.PERSON.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.billa.jooq.tables.pojos.Person> fetchOptionalById(Long value) {
        return fetchOptional(Person.PERSON.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.billa.jooq.tables.pojos.Person> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Person.PERSON.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.billa.jooq.tables.pojos.Person> fetchByName(String... values) {
        return fetch(Person.PERSON.NAME, values);
    }

    /**
     * Fetch records that have <code>age BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.billa.jooq.tables.pojos.Person> fetchRangeOfAge(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Person.PERSON.AGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>age IN (values)</code>
     */
    public List<com.billa.jooq.tables.pojos.Person> fetchByAge(Integer... values) {
        return fetch(Person.PERSON.AGE, values);
    }
}
