/*
 * This file is generated by jOOQ.
 */
package com.billa.jooq;


import com.billa.jooq.tables.Address;
import com.billa.jooq.tables.Employee;
import com.billa.jooq.tables.FlywaySchemaHistory;
import com.billa.jooq.tables.Orders;
import com.billa.jooq.tables.Person;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Billa123 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>billa123</code>
     */
    public static final Billa123 BILLA123 = new Billa123();

    /**
     * The table <code>billa123.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>billa123.employee</code>.
     */
    public final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>billa123.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>billa123.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>billa123.person</code>.
     */
    public final Person PERSON = Person.PERSON;

    /**
     * No further instances allowed
     */
    private Billa123() {
        super("billa123", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Address.ADDRESS,
            Employee.EMPLOYEE,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Orders.ORDERS,
            Person.PERSON
        );
    }
}
