/*
 * This file is generated by jOOQ.
 */
package com.billa.jooq;


import com.billa.jooq.tables.Address;
import com.billa.jooq.tables.Employee;
import com.billa.jooq.tables.FlywaySchemaHistory;
import com.billa.jooq.tables.Orders;
import com.billa.jooq.tables.Person;


/**
 * Convenience access to all tables in billa123.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>billa123.address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>billa123.employee</code>.
     */
    public static final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>billa123.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>billa123.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>billa123.person</code>.
     */
    public static final Person PERSON = Person.PERSON;
}
