/*
 * This file is generated by jOOQ.
 */
package com.billa.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long personId;
    private Integer amount;

    public Address() {}

    public Address(Address value) {
        this.id = value.id;
        this.personId = value.personId;
        this.amount = value.amount;
    }

    public Address(
        Long id,
        Long personId,
        Integer amount
    ) {
        this.id = id;
        this.personId = personId;
        this.amount = amount;
    }

    /**
     * Getter for <code>billa123.address.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>billa123.address.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>billa123.address.person_id</code>.
     */
    public Long getPersonId() {
        return this.personId;
    }

    /**
     * Setter for <code>billa123.address.person_id</code>.
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * Getter for <code>billa123.address.amount</code>.
     */
    public Integer getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>billa123.address.amount</code>.
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Address other = (Address) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.personId == null) {
            if (other.personId != null)
                return false;
        }
        else if (!this.personId.equals(other.personId))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.personId == null) ? 0 : this.personId.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(id);
        sb.append(", ").append(personId);
        sb.append(", ").append(amount);

        sb.append(")");
        return sb.toString();
    }
}
