/*
 * This file is generated by jOOQ.
 */
package com.billa.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private Integer marks;

    public Employee() {}

    public Employee(Employee value) {
        this.id = value.id;
        this.name = value.name;
        this.marks = value.marks;
    }

    public Employee(
        Long id,
        String name,
        Integer marks
    ) {
        this.id = id;
        this.name = name;
        this.marks = marks;
    }

    /**
     * Getter for <code>billa123.employee.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>billa123.employee.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>billa123.employee.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>billa123.employee.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>billa123.employee.marks</code>.
     */
    public Integer getMarks() {
        return this.marks;
    }

    /**
     * Setter for <code>billa123.employee.marks</code>.
     */
    public void setMarks(Integer marks) {
        this.marks = marks;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Employee other = (Employee) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.marks == null) {
            if (other.marks != null)
                return false;
        }
        else if (!this.marks.equals(other.marks))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.marks == null) ? 0 : this.marks.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employee (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(marks);

        sb.append(")");
        return sb.toString();
    }
}
