/*
 * This file is generated by jOOQ.
 */
package com.billa.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Person implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private Integer age;

    public Person() {}

    public Person(Person value) {
        this.id = value.id;
        this.name = value.name;
        this.age = value.age;
    }

    public Person(
        Long id,
        String name,
        Integer age
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
    }

    /**
     * Getter for <code>billa123.person.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>billa123.person.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>billa123.person.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>billa123.person.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>billa123.person.age</code>.
     */
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>billa123.person.age</code>.
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Person other = (Person) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.age == null) {
            if (other.age != null)
                return false;
        }
        else if (!this.age.equals(other.age))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.age == null) ? 0 : this.age.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Person (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);

        sb.append(")");
        return sb.toString();
    }
}
