spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billa123
    username: root
    password: Root@Billa
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG
