/*
 * This file is generated by jOOQ.
 */
package com.billa.jooq.tables.records;


import com.billa.jooq.tables.Employee;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRecord extends UpdatableRecordImpl<EmployeeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>billa123.employee.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>billa123.employee.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>billa123.employee.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>billa123.employee.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>billa123.employee.marks</code>.
     */
    public void setMarks(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>billa123.employee.marks</code>.
     */
    public Integer getMarks() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeRecord
     */
    public EmployeeRecord() {
        super(Employee.EMPLOYEE);
    }

    /**
     * Create a detached, initialised EmployeeRecord
     */
    public EmployeeRecord(Long id, String name, Integer marks) {
        super(Employee.EMPLOYEE);

        setId(id);
        setName(name);
        setMarks(marks);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised EmployeeRecord
     */
    public EmployeeRecord(com.billa.jooq.tables.pojos.Employee value) {
        super(Employee.EMPLOYEE);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setMarks(value.getMarks());
            resetChangedOnNotNull();
        }
    }
}
